[.text-justify]

= Documentation of existing application, third iteration

:icons: font


_Our task consists of creating documentation about the existing application (previous to our takeover), more specifically a class diagram about the iteraction between the classes GameEntity, PlayerState, GameState and Chessboard and a sequence diagram specifying how a new game is created and how a move is managed by the application. More details could be added in a future iteration in order to give a more advanced look into this._

=== Explanation of our class diagram:

_You have below an image showing our class diagram:_

[.text-justify]
GameState is made up of a board (which is loaded from Chessboard). It is also associated to PlayerState as it interactes stores the information about each player. GameEntity interacts with both PlayerState and GameState and is made up of a Board.

Our class diagram contain the following classes:

[.text-justify]
* GameEntity: initializes a chess game using either existing setting (from a saved game) or default settings in order to start a new game. It also stores the infromation about the ongoing game.
* PlayerState: manages all the information relative to the player's remaining time, whether he has lost because he exceeded the time limit, his side (white or black). 
* GameState: manages all the infromation about the state of the game at a given moment. It manages the state of the board (how each piece is placed on the board), who's turn it is to make a move and the information about the state of each player (see class PlayerState)
* ChessBoard: creates a new chessboard if their is no existing board to load in. A board can be loaded in using a string of characters in order to place all the pawns. This string is entered by the user.


image::../Images/GameAndPlayerManagementClassDiagram.SVG[classes,933,800]


=== Explanation of our sequence diagram:

_You have below an image showing our sequence diagram:_

[.text-justify]
This sequence diagram seeks to show how a new game is initialized.

First, the player (user) clicks on "New game" on the chessboard webapp. This prompts the Java server to send a logger message with "POST game/new" which is received by the class GameRessource. This message prompts the CreateGame method (not shown here for pratical purposes) and creates a new instance of a game. GameRessource will also ask for an id associated to this game. This is followed by the sending of the id to the server and then the loading of a chessboard using the default starting pieces and their placement on the board.

When the user moves a chess piece, the server will once again prompt the GameRessource with a POST message. The class will then recover the duration of the move, the instance of the move and will add the move. This will result in the piece being moved on the board.
(NOTE: MoveEntity does not check wether the move is legal or not, this is will be detailed in a futur iteration).

image::../Images/GameEntity_manages_GameState_and_PlayerState_SequenceDiagram.SVG[sequence,933,700]


