= Assisted-Board-Games

Projet maintenu par :
Baylot Eliott, Chen Maryline, Dano Théophile, Peynet Emilie et Piganeau Thaïs
L3 MIAGE en apprentissage

Projet initiallement développé par : 
Brassard Megan, Douo Bougna Delmas, Fremin du Sartel Thibaud et Lourenço Andréa +
MASTER MIAGE SITN en apprentissage
Université Paris Dauphine

image:https://travis-ci.com/busychess/AssistedBoardGames.svg?branch=master["Build Status", link="https://travis-ci.com/busychess/AssistedBoardGames"]

== Description du projet
Dans ce projet, on implémentera le concept d'Assited Board. Ce dernier représente un plateau de jeu ainsi qu'une tablette intéractive par joueur. 

Pour ce projet, on utilisera au maximum les librairies existantes, ainsi que les bonnes pratiques.
Déroulement en 3 itérations

== Specification - Itération 1

- *Tache 1 : Migrer depuis J2E vers JPA/Hibernate, Jersey et Jetty*. Le but de cette tache est de rendre viable l'utilisation du projet quasiment tel quel. => Théophile Dano

- *Tache 2 : Refactoring global du code, changements mineurs et réorganisation de packages, formattage systématique des fichiers*. => Théophile Dano & Maryline Chen

- *Tache 3 : Implémentation d'une WebResource* visant à servir des resources web statiques liées à l'interface du jeu. Une sous-tâche consiste à modifier le fichier JavaScript de l'interface pour faire appel aux bons endpoints.

- *Tache 4 : Migration du front-end vers 2 libs adaptées*. L'objectif ici est de migrer depuis un plateau de jeu codé à la main et pauvre en fonctionnalités vers les bibliothèques chessboard.js et chess.js qui permettent de gérer de manière satisfaisante l'état d'une partie sur le navigateur tout en gardant la flexibilité de contacter le serveur. 

