= Assisted-Board-Games

Projet maintenu par :
Baylot Eliott, Chen Maryline, Dano Théophile, Peynet Emilie et Piganeau Thaïs
L3 MIAGE en apprentissage

Projet initiallement développé par : 
Brassard Megan, Douo Bougna Delmas, Fremin du Sartel Thibaud et Lourenço Andréa +
MASTER MIAGE SITN en apprentissage
Université Paris Dauphine

image:https://travis-ci.com/busychess/AssistedBoardGames.svg?branch=master["Build Status", link="https://travis-ci.com/busychess/AssistedBoardGames"]

== Description du projet
Dans ce projet, on implémentera le concept d'Assited Board. Ce dernier représente un plateau de jeu ainsi qu'une tablette intéractive par joueur. 

Pour ce projet, on utilisera au maximum les librairies existantes, ainsi que les bonnes pratiques.
Déroulement en 3 itérations

== Specification - Itération 1 - Chef de projet : Théophile

- *Tâche 1 : Migrer depuis J2E vers JPA/Hibernate, Jersey et Jetty*. Le but de cette tache est de rendre viable l'utilisation du projet quasiment tel quel. => Théophile Dano

- *Tâche 2 : Refactoring global du code, changements mineurs et réorganisation de packages, formattage systématique des fichiers*. => Théophile Dano & Maryline Chen

- *Tâche 3 : Implémentation d'une WebResource* visant à servir des resources web statiques liées à l'interface du jeu. Une sous-tâche consiste à modifier le fichier JavaScript de l'interface pour faire appel aux bons endpoints.

- *Tâche 4 : Migration du front-end vers 2 libs adaptées*. L'objectif ici est de migrer depuis un plateau de jeu codé à la main et pauvre en fonctionnalités vers les bibliothèques chessboard.js et chess.js qui permettent de gérer de manière satisfaisante l'état d'une partie sur le navigateur tout en gardant la flexibilité de contacter le serveur. 

== Specification - Itération 2 - Chef de projet : Thaïs

- *Tâche 1 : Mise à jour des méthodes HTTP utilisées*

- *Tâche 2 : Rendre les valeurs de retour des endpoints plus cohérentes* (int, JSON pour liste de coups...)

- *Tâche 3 : Création d'un modèle pour les puzzles*

- *Tâche 4 : Ajout d'un aide visuelle aux coups* (surbrillance des cases possibles pour la pièce sélectionnée)

- *Tâche 5 : Rendre les entities immuables*

- *Tâche 6 : Explorer les solutions pour l'horloge de la partie* (différents types d'horloges, représentation...)

- *Tâche 7 : Migrer les endpoints en utilisant un prefix /v1* [retardé]

- *Tâche 8 : Utiliser SLF4J et Logback à la place de JUL* 

- *Tâche 9 : Ajouter des tests unitaires à GameResource* [retardé]

==== Liste des PR

- #24 : Eliott et Thaïs
- #27 : Théophile et Thaïs
- #29 : Emilie et Eliott
- #34 : Eliott et Emilie
- #35 : Eliott et Emilie (abandonnée)
- #36 : Théophile et Thaïs
- #40 : Thaïs
- #37 : Eliott et Emilie
- #38 : Emilie et Eliott
- #39 : surtout Maryline, assistée par Théophile 

== Specifications - Itération 3 - Chef de projet : Emilie

- *Tâche 1 : Ajouter les fonctionnalités de l'itération 2 au frontend* (pas de Java)

- *Tâche 2 : Migrer les endpoints avec le bon prefix api/v1*

- *Tâche 3 : Continuer les tests d'intégration*

- *Tâche 4 : Explorer les solutions pour enregistrer des puzzles* (+ prof)

- *Tâche 5 : Migrer vers des classes génériques GameState et PlayerState* (pour favoriser la réutilisabilité)

- *Tâche 6 : Déployer sur Heroku*

- *Tâche 7 : Restaurer* `GameEntity#addMove`

- *Tâche 8 : Corriger l'utilisation du constructeur MoveDAO*

- *Tâche 9 : Mutualiser PuzzleMoveEntity et MoveEntity*


==== Liste des PR

- Emilie: #41 #46 #37 #38 #52
- Eliott: #48 #51 #49 #50
- Thaïs: #48 #51 #49 #50
- Théophile: #47 #42 #53
- Maryline: #47 #42 #53
