= AssistedBoardGames Cahier des Charges

Par Brassard Megan, Douo Bougna Delmas, Fremin du Sartel Thibaud et Lourenço Andréa +
MASTER MIAGE SITN en apprentissage
Université Paris Dauphine

== Description du projet
Dans ce projet, on implémentera le concept d'Assited Board. Ce dernier représente un plateau de jeu ainsi qu'une tablette intéractive par joueur. + 

Pour ce projet, on utilisera au maximum les librairies existantes, ainsi que les bonnes pratiques.

== Déroulement en 3 itérations
=== Specification - Itération 1

Tâche 1 : ChessStateTxt +
Tâche 2 : ChessMoveTxt +
Tâche 3 : SetDB +
Tâche 4 : ShowClient + 

Description générale : Mise en place des bases du projet (état, mouvement et base de données)

=== Specification - Itération 2

Tâche 1 : StateServlet +
Tâche 2 : ObjectsXml +
Tâche 3 : UseDB +
Tâche 4 : Player +
Tâche 5 : AddServlets +

Description générale : Ajout des servlets (d'état, de calculs d'état à partir d'un mouvement, représentation du jeu) + implémentation BDD

=== Specification - Itération 3

Tâche 1 : SendMessage +
Tâche 2 : Help +
Tâche 3 : HelpAsync +
Tâche 4 : Online +
Tâche 5 : ExtServletState +

Description générale : Mise en place de la suggestion online, améliorer les servlets
