= Assisted-Board-Games
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: assisted-board-games
:repository: Assisted-Board-Games

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 and M2 MIAGE).

The code is hereby published under the MIT License, with their permission.

Projet maintenu par :
Amoussou Dahuiss, Atangana Marina, Burton James, Demay Aaron, Hamnache Yasmine, Hudayberdiyev Kerim, Shaikh Yunus Anam +
L3 MIAGE en apprentissage
image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]


Projet initiallement développé par : 
Brassard Megan, Douo Bougna Delmas, Fremin du Sartel Thibaud et Lourenço Andréa +
MASTER MIAGE SITN en apprentissage
Université Paris Dauphine

image:https://travis-ci.org/busychess/Assisted-Board-Games.svg?branch=master["Build Status", link="https://travis-ci.org/busychess/Assisted-Board-Games"]


== Description du projet
Dans ce projet, on implémentera le concept d'Assited Board. Ce dernier représente un plateau de jeu ainsi qu'une tablette intéractive par joueur. 

Pour ce projet, on utilisera au maximum les librairies existantes, ainsi que les bonnes pratiques.
Déroulement en  itérations

== Specification - Itération 1 - Chef de projet : Atangana Marina

- Tâche 1 : Création d'un diagramme de classe du menu d'Assisted Board Games. L'objectif de cette tâche est de représenter les différentes fonctions qui permettront à l'utilisateur d'accéder aux différents jeux. => Amoussou Dahuiss et Burton James

- Tâche 2 : Création d'un diagramme de cas d’utilisation du Play Board Games  => Hamnache Yasmine et Demay Aaron

- Tâche 3 : Création des classes filles du jeu d'échecs et de dames qui héritent de la classe GameEntity => Hudayberdiyev Kerim et Shaikh Yunus Anam



==== Liste des PR

- #1 : Amoussou Dahuiss et Burton James
- #2 : Hudayberdiyev Kerim et Shaikh Yunus Anam
- #3 : Hamnache Yasmine et Demay Aaron

