= Assisted-Board-Games
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: assisted-board-games
:repository: Assisted-Board-Games

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 and M2 MIAGE).

The code is hereby published under the MIT License, with their permission.

Project maintained by :
Amoussou Dahuiss, Atangana Marina, Burton James, Demay Aaron, Hamnache Yasmine, Hudayberdiyev Kerim, Shaikh Yunus Anam +
L3 MIAGE in Apprenticeship

== Project description
In this project, the concept of the Assited Board will be implemented. The latter represents a game board as well as an interactive tablet for each player. 

For this project, we will make maximum use of existing libraries and good practices.
Development in iterations.

== Specification - Iteration 1 - Project leader: Atangana Marina

- Focus : Creation of Menu => Task 1: Creation of a class diagram of the Assisted Board Games menu. The objective of this task is to represent the different functions that will allow the user to access the different games. => Amoussou Dahuiss and Burton James

- Focus : Complete the documentation => Task 2: Creation of a Play Board Games Use Case Diagram and Game Entity Class => Hamnache Yasmine and Demay Aaron

- Focus : Complete daughter classes =>  Task 3 : Creation of the daughter classes of chess and draughts that inherit the GameEntity class => Hudayberdiyev Kerim and Shaikh Yunus Anam

==== List of PR

- #T_Menu: Amoussou Dahuiss and Burton James
- #Generalization, Inheritance and Reusabily: Hudayberdiyev Kerim and Shaikh Yunus Anam
- #Movesuggestion: Hamnache Yasmine and Demay Aaron
