= Sample Quarkus on Heroku
:groupId: io.github.oliviercailloux
:artifactId: sample-quarkus-heroku
:repository: Sample-Quarkus-Heroku

A simple JAX-RS server configured by https://quarkus.io/[Quarkus], with JPA with Hibernate, CDI… Ready to be deployed to Heroku.

To deploy to Heroku, simply follow their https://devcenter.heroku.com/articles/getting-started-with-java[tutorial], replacing their example application with this one: instead of `git clone \https://github.com/heroku/java-getting-started`, type `git clone \https://github.com/oliviercailloux/{repository}.git`.

See this (impressive) application live https://{artifactId}.herokuapp.com[here]. (You might have to wait for about thirty seconds, the time required for Heroku to wake up the application, if it is https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping[asleep] at the time you click.)

== Local configuration file
To develop and test your application locally, create a file named `.env` and set the following properties.

----
quarkus.http.port = 8080
quarkus.datasource.username = …
quarkus.datasource.password = …
quarkus.datasource.jdbc.url = jdbc:postgresql://….compute.amazonaws.com:…/…
quarkus.log.file.enable = true
quarkus.log.file.level = DEBUG
----

To find the URL of your datasource, log on your Heroku interface, click on your app, go to settings and click on "Reveal Config Vars".

The URL is formatted in the following way, the credentials are in your URL :

`postgres://<username>:<password>@<hostname/server>/<databasename>`

Now that you have retrieved your credentials, you have to change the URL to match the Postgres JDBC convention according to the heroku https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-database_url-in-plain-jdbc[documentation]
