= Assisted-Board-Games
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: assisted-board-games
:repository: Assisted-Board-Games

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

//image:https://github.com/{gitHubUserName}/{repository}/workflows/Java%20CI%20with%20Maven/badge.svg?branch=master["Build Status", link="https://github.com/{gitHubUserName}/{repository}/actions"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in https://dauphine.psl.eu/en/training/bachelors-degrees/organizational-computer-science/bachelors3-business-informatics/program[MIAGE L3 Alternance]).

The code is hereby published under the https://github.com/oliviercailloux/{repository}/blob/master/LICENSE[MIT License], with their permission.

See the https://github.com/oliviercailloux/{repository}/blob/master/Doc/README.adoc[doc].

== Sample Quarkus on Heroku
To deploy to Heroku, simply follow their https://devcenter.heroku.com/articles/getting-started-with-java[tutorial], replacing their example application with this one: instead of `git clone \https://github.com/heroku/java-getting-started`, type `git clone \https://github.com/oliviercailloux/{repository}.git`.

== Local configuration file
To develop and test your application locally, create a file named `.env` and set the following properties.

----
quarkus.http.port = 8080
quarkus.datasource.username = …
quarkus.datasource.password = …
quarkus.datasource.jdbc.url = jdbc:postgresql://….compute.amazonaws.com:…/…
quarkus.log.file.enable = true
quarkus.log.file.level = DEBUG
----

To find the URL of your datasource, log on your https://id.heroku.com/login[Heroku interface], click on your app, go to settings and click on "Reveal Config Vars".

The URL is formatted in the following way, the credentials are in your URL :

`postgres://<username>:<password>@<hostname/server>/<databasename>`

Now that you have retrieved your credentials, you have to change the URL to match the Postgres JDBC convention according to the heroku https://devcenter.heroku.com/articles/connecting-to-relational-databases-on-heroku-with-java#using-the-database_url-in-plain-jdbc[documentation]
