= CheckerBoard, Piece and Square Classes

_In order to manage logic behind checkers game we need the following Classes: `CheckerBoard` - representation of a board, `Piece` - representation of pieces and `Square` - representation of a square on a board._

== CheckerBoard

* This implementation of a CheckerBoard is based on a `Manoury's notation` described by the website http://www.ffjd.fr/Web/index.php?page=notation[source: FFJD - Fédération Française], which helps to facilitate the implementation of `Square` class.

* Two static factory methods are provided to create an instance of a CheckerBoard : either default one using *newInstance()*, which is the default representation of a CheckerBoard at the start of the game or another one *given()* which accepts a predefined Map.

== Piece

* Several static factory methods are available in order to create directly white pieces with the method `white()` and black pieces with the method `black()`. We can also create now white Queen with the method `whiteQueen()` and black Quenn with the method `blackQueen()`.

== Square

* Square number can be any positive number between *1* and *50* (included). Convenience methods are provided in this Class.

* In addition, *unit tests*, contained in *checkers* package run *3* tests which cover different scenarios, in order to ensure the proper functioning of `Piece`,`Square` and `CheckerBoard` Classes.

The implemented classes with the Java code are contained in `checkers` package.
