= Creation of Square, Piece class and an interface CheckerBoard for the checkers game.

Marina & Dahuiss

_Our task consists on creation of two classes : Square and Piece for the checkers game and also an interface which explains mainly how we will represent the CheckersBoard._

* First of all we create the class Square in which we have 2 parameters which define the coordinates of the square and also an instance of Piece. 
  We use it to know if the square is empty or not. This class will be useful to build our checkers board and also to place the pieces on the right squares.

* In a second step, we have created a class that represents a piece of the game of checkers.
  This class contains 2 parameters : the color of the piece representing by a String and also a boolean promoted which allows us to know if the piece is promoted or not.
  By promoted we mean if the piece becomes a 'Queen' or not. 

* The other part of our work consists on creating an interface which explains how we want to create the CheckerBoard. 
  In our interface we can find many methods such as printBoard(), generatePoints() and others. 
  All those methods will allow us to create the CheckersBoard. 

_We have to notice that it's just the beggining of our idea an we can improve it later in this project._

You can find our classes in this https://github.com/oliviercailloux-org/projet-assisted-board-games-1/tree/IterationSquareJava/src/main/java/io/github/oliviercailloux/assisted_board_games/checkers[package].



