= Resources

== GameResource Class
In order to retrieve and send the games setups, this class communicates with the database using *POST* and *GET* requests.

 - `createGame` creates a new game by taking into account the time and the increment chosen by the players. The method calls the *_GameEntity_* class  to instantiate a game into the Database before returning the game ID. (It is a  POST query with the route : api/v1/game/new)
 - `getGame` takes an instantiated game *ID* as a parameter and then calls the *_getMoves()_* method in order to get the moves already saved in the database before returning the FEN that describes the particular board position of the instantiated chess game in question. (It is a GET query with the route : api/v1/game/{gameId})
 - `getMoves` calls the *_MoveEntity_* class that records every move from a start position `from` to a finish position `to`. (It is a GET query with the route : api/v1/game/{gameId}/moves)
 - `getPlayerRemainingTime` identifies a player from the Game ID and the side put as parameters. The method calls the *_PlayerState_* class that stores some attributes of a player including its remaining time in the game that will be returned by this method. (It is a GET query with the route : api/v1/game/{gameId}/clock/{side})
 - `addMoves` takes a game ID and a move as parameters before sending the move to the Database. (It is a POST query with the route : api/v1/game/{gameId}/move)

== HelpResource Class
This class communicates with database by sending *GET* requets in order to help players in their game by indicating their next possible moves.  

 - `suggestMove` retrieves a game ID put as a parameter and to determine the current state of the game including the moves already saved from this game. After that, it calls the *_generateLegalMoves()_* method from the `chesslib` library to store the list of legal moves. Then, the methods *_isMated()_* and *_isStaleMate()_* are also called from the previous library to determine if some of the legal moves could generate a mate or a stalemate. Finally, the method retuns the three lists of possible moves for the actual state of the game. (It is a GET query with the route : api/v1/help)
